######LANDSCAPE ANALYSIS
###Load packages
library(sf) # Core vector GIS data package
library(raster) # Core raster GIS data package
library(rgeos) # Extends vector data functionality
library(rgdal) # Interface to the Geospatial Data Abstraction Library
library(lwgeom) # Extends vector data functionality
library(viridisLite)
library(viridis) 
library(maps)
library(maptools)
library(gridExtra)
library(spatialEco)
library(magrittr) 
library(dplyr)
library(funModeling)
library(mapview)
library(purrr)
library(gdistance)
library(ggplot2)

##Set working directory##
setwd("C:/Users/acs119/OneDrive - Imperial College London/ICL/Thesis/Landscape_analysis")

###Import study points 
point<- st_read("puntos_07_17/puntos_07_17.shp")
point<- point%>% st_as_sf(coords = c("Long", "Lat"), dim = "XY")
point<- st_transform(point, crs = 4326) ##transform to lat long projection
st_crs(point)
plot(point["Country"])

# Create buffer (1km ~ 1000m)
buffer <- st_buffer(point, dist = 0.02)

##Calculate the area of each buffer 
buffer<- buffer%>%mutate(area_m2 = st_area(buffer))
class(buffer)
st_crs(buffer)

##Filter points by year of publication
#2011-2019
point2011_2019<- point%>%filter(Year>= 2011)
point2011_2019<-st_sf(point2011_2019)
point2011_2019<- st_transform(point2011_2019, crs = 4326)
class(point2011_2019)
st_crs(point2011_2019) ##to know the coordinate reference system
plot(point2011_2019["Country"]) ##to plot the points

#2001-2010
point2001_2010<- point%>%filter(Year>= 2001 & Year<2011)
point2001_2010<-st_sf(point2001_2010)
point2001_2010<- st_transform(point2001_2010, crs = 4326)
class(point2001_2010)
st_crs(point2001_2010) ##to know the coordinate reference system
plot(point2001_2010["Country"]) ##to plot the points

#1986-2000
point1986_2000<- point%>%filter(Year<= 2000)
point1986_2000<-st_sf(point1986_2000)
point1986_2000<- st_transform(point1986_2000, crs = 4326)
class(point1986_2000)
st_crs(point1986_2000) ##to know the coordinate reference system
plot(point1986_2000["Country"]) ##to plot the points

##Filter buffers by year of publication
#2011-2019
buffer2011_2019<- buffer%>%filter(Year>= 2011)
buffer2011_2019<-st_sf(buffer2011_2019)
st_crs(buffer2011_2019)
buffer2011_2019<- st_transform(buffer2011_2019, crs = 4326)
plot(buffer2011_2019["Country"])

#2001-2010
buffer2001_2010<- buffer%>%filter(Year>= 2001 & Year<2011)
buffer2001_2010<-st_sf(buffer2001_2010)
st_crs(buffer2001_2010)
buffer2001_2010<- st_transform(buffer2001_2010, crs = 4326)
plot(buffer2001_2010["Country"])

#1986-2000
buffer1986_2000<- buffer%>%filter(Year<= 2000)
buffer1986_2000<-st_sf(buffer1986_2000)
st_crs(buffer1986_2000)
buffer1986_2000<- st_transform(buffer1986_2000, crs = 4326)
plot(buffer1986_2000["Country"])

##Calculate the area of each buffer
#2011-2019
buffer2011_2019<- buffer2011_2019%>%mutate(area_m2 =st_area(buffer2011_2019))
class(buffer2011_2019)
st_crs(buffer2011_2019)

#2001-2010
buffer2001_2010<- buffer2001_2010%>%mutate(area_m2 =st_area(buffer2001_2010))
class(buffer2001_2010)
st_crs(buffer2001_2010)

#1986-2000
buffer2001_2010<- buffer2001_2010%>%mutate(area_m2 =st_area(buffer2001_2010))
class(buffer2001_2010)
st_crs(buffer2001_2010)

######Import vectors generated by supervised classification in Google Earth Engine
##https://gis.stackexchange.com/questions/137621/join-spatial-point-data-to-polygons-in-r

##list all the shapefiles within the folder location
## tutorial: https://stackoverflow.com/questions/53507133/combining-multiple-shapefiles-in-r
#2011-2019
file_list2011_2019 <- list.files("C:/Users/acs119/OneDrive - Imperial College London/ICL/Thesis/Landscape_analysis/Vectores_2011-2019_07.17",
                                 pattern = ".shp", full.names = TRUE)
class(file_list2011_2019)

#2001-2010
file_list2001_2010 <- list.files("C:/Users/acs119/OneDrive - Imperial College London/ICL/Thesis/Landscape_analysis/Vectores_2001-2010_07.17",
                                 pattern = ".shp", full.names = TRUE)
class(file_list2001_2010)

#1986-2000
file_list1986_2000 <- list.files("C:/Users/acs119/OneDrive - Imperial College London/ICL/Thesis/Landscape_analysis/Vectores_1986-2000_07.17",
                                 pattern = ".shp", full.names = TRUE)
class(file_list1986_2000)

##Read all shapefiles, store as a list
#2011-2019
shapefile_list2011_2019 <- lapply(file_list2011_2019, read_sf)
shapefile_list2011_2019

#2001-2010
shapefile_list2001_2010 <- lapply(file_list2001_2010, read_sf)
shapefile_list2001_2010

#1986-2000
shapefile_list1986_2000 <- lapply(file_list1986_2000, read_sf)
shapefile_list1986_2000

##Combine all classified vectors in only one vector
#Tutorial: https://stackoverflow.com/questions/51312935/convert-a-list-of-sf-objects-into-one-sf
#2011-2019
vectors2011_2019<- do.call(rbind, shapefile_list2011_2019)
vectors2011_2019
vectors2011_2019<-st_sf(vectors2011_2019)
vectors2011_2019<- st_transform(vectors2011_2019, crs = 4326)
#vectors2011_2019<- st_transform(vectors2011_2019, crs = code)
class(vectors2011_2019)
plot(vectors2011_2019["count"])
st_crs(vectors2011_2019)
sf_proj_info("vectors2011_2019")

#2001-2010
vectors2001_2010<- do.call(rbind, shapefile_list2001_2010)
vectors2001_2010
vectors2001_2010<-st_sf(vectors2001_2010)
vectors2001_2010<- st_transform(vectors2001_2010, crs = 4326)
#vectors2001_2010<- st_transform(vectors2001_2010, crs = code)
class(vectors2001_2010)
plot(vectors2001_2010["count"])
st_crs(vectors2001_2010)
sf_proj_info("vectors2001_2010")

#1986-2000
vectors1986_2000<- do.call(rbind, shapefile_list1986_2000)
vectors1986_2000
vectors1986_2000<-st_sf(vectors1986_2000)
vectors1986_2000<- st_transform(vectors1986_2000, crs = 4326)
#vectors1986_2000<- st_transform(vectors1986_2000, crs = code)
class(vectors1986_2000)
plot(vectors1986_2000["count"])
st_crs(vectors1986_2000)
sf_proj_info("vectors1986_2000")

###Join to add a identification column in the classified vector
#2011-2019
class(vectors2011_2019)
class(buffer2011_2019)
join2011_2019 <- st_join(vectors2011_2019, buffer2011_2019["Landscape_"], left = TRUE) # join points
join2011_2019<-st_sf(join2011_2019)
join2011_2019<- st_transform(join2011_2019, crs = 4326)
st_as_sf(join2011_2019)
print(join2011_2019)
class(join2011_2019)

#2001-2010
class(vectors2001_2010)
class(buffer2001_2010)
join2001_2010 <- st_join(vectors2001_2010, buffer2001_2010["Landscape_"], left = TRUE) # join points
join2001_2010<-st_sf(join2001_2010)
join2001_2010<- st_transform(join2001_2010, crs = 4326)
st_as_sf(join2001_2010)
print(join2001_2010)
class(join2001_2010)

#1986-2000
class(vectors1986_2000)
class(buffer1986_2000)
join1986_2000 <- st_join(vectors1986_2000, buffer1986_2000["Landscape_"], left = TRUE) # join points
join1986_2000<-st_sf(join1986_2000)
join1986_2000<- st_transform(join1986_2000, crs = 4326)
st_as_sf(join1986_2000)
print(join1986_2000)
class(join1986_2000)

#Export the join vector as shape or gpkg
#https://mgimond.github.io/Spatial/reading-and-writing-spatial-data-in-r.html
#st_write(join2011_2019, dsn="join2011_2019.gpkg", layer = "join2011_2019.gpkg", driver="GPKG")  # Create a geopackage file
#st_write(join2011_2019, dsn="join2011_2019_07.20.shp", layer = "join2011_2019.shp", driver="ESRI Shapefile")  # Create a shape file
#st_write(join2001_2010, dsn="join2001_2010_07.20.shp", layer = "join2001_2010.shp", driver="ESRI Shapefile")  # Create a shape file
#st_write(join1986_2000, dsn="join1986_2000_07.20.shp", layer = "join1986_2000.shp", driver="ESRI Shapefile")  # Create a shape file

##Calculate the area of each polygon 
#2011-2019
area2011_2019<- join2011_2019%>%mutate(area_m2 =st_area(join2011_2019))
class(area2011_2019)
area2011_2019_df<- fortify(area2011_2019)
area2011_2019_df<- as.data.frame(area2011_2019_df)%>% dplyr::select(1:3,5) ## Convert shapefile to data.frame
class(area2011_2019_df)

#2001-2010
area2001_2010<- join2001_2010%>%mutate(area_m2 =st_area(join2001_2010))
class(area2001_2010)
area2001_2010_df<- fortify(area2001_2010)
area2001_2010_df<- as.data.frame(area2001_2010_df)%>% dplyr::select(1:3,5) ## Convert shapefile to data.frame
class(area2001_2010_df)

#1986-2000
area1986_2000<- join1986_2000%>%mutate(area_m2 =st_area(join1986_2000))
class(area1986_2000)
area1986_2000_df<- fortify(area1986_2000)
area1986_2000_df<- as.data.frame(area1986_2000_df) %>% dplyr::select(1:3,5) ## Convert shapefile to data.frame
class(area1986_2000_df)

###Calculate distante from the centre of the plot to the nearest natural area
#https://stackoverflow.com/questions/53854803/calculate-minimum-distance-between-multiple-polygons-with-r
#2011-2019
natural.join2011_2019<- join2011_2019%>% filter(classNames == "0")
near.point2011_2019<- st_nearest_points(point2011_2019, natural.join2011_2019)
class(near.point2011_2019)
near.point2011_2019<-st_sf(near.point2011_2019)
near.point2011_2019<- st_transform(near.point2011_2019, crs = 4326)
near.point2011_2019$length<- st_length(near.point2011_2019)
near.point2011_2019<-st_sf(near.point2011_2019)
near.point2011_2019<- st_transform(near.point2011_2019, crs = 4326)

class(near.point2011_2019)
class(point2011_2019)
distance.join2011_2019 <- st_join(near.point2011_2019, point2011_2019["Landscape_"], left = TRUE) # join points
distance.join2011_2019<-st_sf(distance.join2011_2019)
distance.join2011_2019<- st_transform(distance.join2011_2019, crs = 4326)
st_as_sf(distance.join2011_2019)
print(distance.join2011_2019)
class(distance.join2011_2019)

distance2011_2019.df<- fortify(distance.join2011_2019)
distance2011_2019.df<- as.data.frame(distance2011_2019.df)%>%dplyr::select(1:2)

min_distance2011_2019<- distance2011_2019.df%>%group_by(Landscape_)%>%
  mutate(min_distance = min(length))%>%
  distinct(Landscape_, .keep_all = TRUE)

#2001-2010
natural.join2001_2010<- join2001_2010%>% filter(classNames == "0")
near.point2001_2010<- st_nearest_points(point2001_2010, natural.join2001_2010)
class(near.point2001_2010)
near.point2001_2010<-st_sf(near.point2001_2010)
near.point2001_2010<- st_transform(near.point2001_2010, crs = 4326)
near.point2001_2010$length<- st_length(near.point2001_2010)
near.point2001_2010<-st_sf(near.point2001_2010)
near.point2001_2010<- st_transform(near.point2001_2010, crs = 4326)

class(near.point2001_2010)
class(point2001_2010)
distance.join2001_2010 <- st_join(near.point2001_2010, point2001_2010["Landscape_"], left = TRUE) # join points
distance.join2001_2010<-st_sf(distance.join2001_2010)
distance.join2001_2010<- st_transform(distance.join2001_2010, crs = 4326)
st_as_sf(distance.join2001_2010)
print(distance.join2001_2010)
class(distance.join2001_2010)

distance2001_2010.df<- fortify(distance.join2001_2010)
distance2001_2010.df<- as.data.frame(distance2001_2010.df)%>%dplyr::select(1:2)

min_distance2001_2010<- distance2001_2010.df%>%group_by(Landscape_)%>%
  mutate(min_distance = min(length))%>%
  distinct(Landscape_, .keep_all = TRUE)

#1986-2000
natural.join1986_2000<- join1986_2000%>% filter(classNames == "0")
near.point1986_2000<- st_nearest_points(point1986_2000, natural.join1986_2000)
class(near.point1986_2000)
near.point1986_2000<-st_sf(near.point1986_2000)
near.point1986_2000<- st_transform(near.point1986_2000, crs = 4326)
near.point1986_2000$length<- st_length(near.point1986_2000)
near.point1986_2000<-st_sf(near.point1986_2000)
near.point1986_2000<- st_transform(near.point1986_2000, crs = 4326)

class(near.point1986_2000)
class(point1986_2000)
distance.join1986_2000 <- st_join(near.point1986_2000, point1986_2000["Landscape_"], left = TRUE) # join points
distance.join1986_2000<-st_sf(distance.join1986_2000)
distance.join1986_2000<- st_transform(distance.join1986_2000, crs = 4326)
st_as_sf(distance.join1986_2000)
print(distance.join1986_2000)
class(distance.join1986_2000)

distance1986_2000.df<- fortify(distance.join1986_2000)
distance1986_2000.df<- as.data.frame(distance1986_2000.df)%>%dplyr::select(1:2)

min_distance1986_2000<- distance1986_2000.df%>%group_by(Landscape_)%>%
  mutate(min_distance = min(length))%>%
  distinct(Landscape_, .keep_all = TRUE)

#Export shape files nearest distance
#st_write(distance.join12011_2019, dsn="distance.join12011_2019_07.21.shp", layer = "distance.join12011_2019.shp", driver="ESRI Shapefile")
#st_write(distance.join12001_2010, dsn="distance.join12001_2010_07.21.shp", layer = "distance.join12001_2010.shp", driver="ESRI Shapefile")
#st_write(distance.join1986_2000, dsn="distance.join2011_2019_07.21.shp", layer = "distance.join2011_2019.shp", driver="ESRI Shapefile")

##############SPECIAL CASES ###############################################
#######2011-2019
#133 (19.20611111	-96.88444444)
buffer133_2<- buffer%>%filter(Landscape_ == "133_Mexico_north america_19.20611111_-96.88444444")
buffer133_2<-st_sf(buffer133_2)
st_crs(buffer133_2)
buffer133_2<- st_transform(buffer133_2, crs = 4326)
plot(buffer133_2["Country"])
study_133_2<- st_read("Vectores_2011-2019_07.17/L8vector_study_133_2.shp")
study_133_2<-st_sf(study_133_2)
study_133_2<- st_transform(study_133_2, crs = 4326)
plot(study_133_2["classNames"], col= c("yellow","green",  "red"))
class(study_133_2)
class(buffer133_2)
join133_2 <- st_join(study_133_2, buffer133_2["Landscape_"], left = TRUE) # join points
join133_2<-st_sf(join133_2)
join133_2<- st_transform(join133_2, crs = 4326)
st_as_sf(join133_2)
print(join133_2)
class(join133_2)
area133_2<- join133_2%>%mutate(area_m2 =st_area(join133_2))
class(join133_2)
area133_2_df<- fortify(area133_2)
area133_2_df<- as.data.frame(area133_2_df) %>% dplyr::select(1:3,5)

natural.join133_2<- natural.join2011_2019%>%filter(Landscape_ == "133_Mexico_north america_19.20611111_-96.88444444")
point133_2<- point2011_2019%>%filter(Landscape_ == "133_Mexico_north america_19.20611111_-96.88444444")
near.point133_2<- st_nearest_points(point133_2, natural.join133_2)
class(near.point133_2)
near.point133_2<-st_sf(near.point133_2)
near.point133_2<- st_transform(near.point133_2, crs = 4326)
near.point133_2$length<- st_length(near.point133_2)
near.point133_2<-st_sf(near.point133_2)
near.point133_2<- st_transform(near.point133_2, crs = 4326)

class(near.point133_2)
class(point133_2)
distance.join133_2 <- st_join(near.point133_2, point133_2["Landscape_"], left = TRUE) # join points
distance.join133_2<-st_sf(distance.join133_2)
distance.join133_2<- st_transform(distance.join133_2, crs = 4326)
st_as_sf(distance.join133_2)
print(distance.join133_2)
class(distance.join133_2)

distance.join133_2.df<- fortify(distance.join133_2)
distance.join133_2.df<- as.data.frame(distance.join133_2.df)%>%dplyr::select(1:2)

min_distance133_2<- distance.join133_2.df%>%group_by(Landscape_)%>%
  mutate(min_distance = min(length))%>%
  distinct(Landscape_, .keep_all = TRUE)

data133_2_df<- right_join(x=min_distance133_2 , y=area133_2_df, by="Landscape_")

#133 (19.21583333	-96.88527778)
buffer133_5<- buffer%>%filter(Landscape_ == "133_Mexico_north america_19.21583333_-96.88527778")
buffer133_5<-st_sf(buffer133_5)
st_crs(buffer133_5)
buffer133_5<- st_transform(buffer133_5, crs = 4326)
plot(buffer133_5["Country"])
study_133_5<- st_read("Vectores_2011-2019_07.17/L8vector_study_133_5.shp")
study_133_5<-st_sf(study_133_5)
study_133_5<- st_transform(study_133_5, crs = 4326)
plot(study_133_5["classNames"], col= c("yellow","green",  "red"))
class(study_133_5)
class(study_133_5)
join133_5 <- st_join(study_133_5, buffer133_5["Landscape_"], left = TRUE) # join points
join133_5<-st_sf(join133_5)
join133_5<- st_transform(join133_5, crs = 4326)
st_as_sf(join133_5)
print(join133_5)
class(join133_5)
area133_5<- join133_5%>%mutate(area_m2 =st_area(join133_5))
class(area133_5)
area133_5_df<- fortify(area133_5)
area133_5_df<- as.data.frame(area133_5_df) %>% dplyr::select(1:3,5)

natural.join133_5<- natural.join2011_2019%>%filter(Landscape_ == "133_Mexico_north america_19.21583333_-96.88527778")
point133_5<- point2011_2019%>%filter(Landscape_ == "133_Mexico_north america_19.21583333_-96.88527778")
near.point133_5<- st_nearest_points(point133_5, natural.join133_5)
class(near.point133_5)
near.point133_5<-st_sf(near.point133_5)
near.point133_5<- st_transform(near.point133_5, crs = 4326)
near.point133_5$length<- st_length(near.point133_5)
near.point133_5<-st_sf(near.point133_5)
near.point133_5<- st_transform(near.point133_5, crs = 4326)

class(near.point133_5)
class(point133_5)
distance.join133_5 <- st_join(near.point133_5, point133_5["Landscape_"], left = TRUE) # join points
distance.join133_5<-st_sf(distance.join133_5)
distance.join133_5<- st_transform(distance.join133_5, crs = 4326)
st_as_sf(distance.join133_5)
print(distance.join133_5)
class(distance.join133_5)

distance.join133_5.df<- fortify(distance.join133_5)
distance.join133_5.df<- as.data.frame(distance.join133_5.df)%>%dplyr::select(1:2)

min_distance133_5<- distance.join133_5.df%>%group_by(Landscape_)%>%
  mutate(min_distance = min(length))%>%
  distinct(Landscape_, .keep_all = TRUE)

data133_5_df<- right_join(x=min_distance133_5 , y=area133_5_df, by="Landscape_")

#133 (19.46638889	-96.93416667)
buffer133_3<- buffer%>%filter(Landscape_ == "133_Mexico_north america_19.46638889_-96.93416667")
buffer133_3<-st_sf(buffer133_3)
st_crs(buffer133_3)
buffer133_3<- st_transform(buffer133_3, crs = 4326)
plot(buffer133_3["Country"])
study_133_3<- st_read("Vectores_2011-2019_07.17/L8vector_study_133_3.shp")
study_133_3<-st_sf(study_133_3)
study_133_3<- st_transform(study_133_3, crs = 4326)
plot(study_133_3["classNames"], col= c("yellow","green",  "red"))
class(study_133_3)
class(buffer133_3)
join133_3 <- st_join(study_133_3, buffer133_3["Landscape_"], left = TRUE) # join points
join133_3<-st_sf(join133_3)
join133_3<- st_transform(join133_3, crs = 4326)
st_as_sf(join133_3)
print(join133_3)
class(join133_3)
area133_3<- join133_3%>%mutate(area_m2 =st_area(join133_3))
class(area133_3)
area133_3_df<- fortify(area133_3)
area133_3_df<- as.data.frame(area133_3_df) %>% dplyr::select(1:3,5)

natural.join133_3<- natural.join2011_2019%>%filter(Landscape_ == "133_Mexico_north america_19.46638889_-96.93416667")
point133_3<- point2011_2019%>%filter(Landscape_ == "133_Mexico_north america_19.46638889_-96.93416667")
near.point133_3<- st_nearest_points(point133_3, natural.join133_3)
class(near.point133_3)
near.point133_3<-st_sf(near.point133_3)
near.point133_3<- st_transform(near.point133_3, crs = 4326)
near.point133_3$length<- st_length(near.point133_3)
near.point133_3<-st_sf(near.point133_3)
near.point133_3<- st_transform(near.point133_3, crs = 4326)

class(near.point133_3)
class(point133_3)
distance.join133_3 <- st_join(near.point133_3, point133_3["Landscape_"], left = TRUE) # join points
distance.join133_3<-st_sf(distance.join133_3)
distance.join133_3<- st_transform(distance.join133_3, crs = 4326)
st_as_sf(distance.join133_3)
print(distance.join133_3)
class(distance.join133_3)

distance.join133_3.df<- fortify(distance.join133_3)
distance.join133_3.df<- as.data.frame(distance.join133_3.df)%>%dplyr::select(1:2)

min_distance133_3<- distance.join133_3.df%>%group_by(Landscape_)%>%
  mutate(min_distance = min(length))%>%
  distinct(Landscape_, .keep_all = TRUE)

data133_3_df<- right_join(x=min_distance133_3 , y=area133_3_df, by="Landscape_")

#18 (19.455055	-96.92654)
buffer18_2<- buffer%>%filter(Landscape_ == "18_Mexico_north america_19.455055_-96.92654")
buffer18_2<-st_sf(buffer18_2)
st_crs(buffer18_2)
buffer18_2<- st_transform(buffer18_2, crs = 4326)
plot(buffer18_2["Country"])
study_18_2<- st_read("Vectores_2011-2019_07.17/L8vector_study_18_2.shp")
study_18_2<-st_sf(study_18_2)
study_18_2<- st_transform(study_18_2, crs = 4326)
plot(study_18_2["classNames"], col= c("yellow","green",  "red"))
class(study_18_2)
class(buffer18_2)
join18_2 <- st_join(study_18_2, buffer18_2["Landscape_"], left = TRUE) # join points
join18_2<-st_sf(join18_2)
join18_2<- st_transform(join18_2, crs = 4326)
st_as_sf(join18_2)
print(join18_2)
class(join18_2)
area18_2<- join18_2%>%mutate(area_m2 =st_area(join18_2))
class(area18_2)
area18_2_df<- fortify(area18_2)
area18_2_df<- as.data.frame(area18_2_df) %>% dplyr::select(1:3,5)

natural.join18_2<- natural.join2011_2019%>%filter(Landscape_ == "18_Mexico_north america_19.455055_-96.92654")
point18_2<- point2011_2019%>%filter(Landscape_ == "18_Mexico_north america_19.455055_-96.92654")
near.point18_2<- st_nearest_points(point18_2, natural.join18_2)
class(near.point18_2)
near.point18_2<-st_sf(near.point18_2)
near.point18_2<- st_transform(near.point18_2, crs = 4326)
near.point18_2$length<- st_length(near.point18_2)
near.point18_2<-st_sf(near.point18_2)
near.point18_2<- st_transform(near.point18_2, crs = 4326)

class(near.point18_2)
class(point18_2)
distance.join18_2 <- st_join(near.point18_2, point18_2["Landscape_"], left = TRUE) # join points
distance.join18_2<-st_sf(distance.join18_2)
distance.join18_2<- st_transform(distance.join18_2, crs = 4326)
st_as_sf(distance.join18_2)
print(distance.join18_2)
class(distance.join18_2)

distance.join18_2.df<- fortify(distance.join18_2)
distance.join18_2.df<- as.data.frame(distance.join18_2.df)%>%dplyr::select(1:2)

min_distance18_2<- distance.join18_2.df%>%group_by(Landscape_)%>%
  mutate(min_distance = min(length))%>%
  distinct(Landscape_, .keep_all = TRUE)

data18_2_df<- right_join(x=min_distance18_2 , y=area18_2_df, by="Landscape_")

####2001-2010
#132 (15.15874	-92.31623)
buffer132_1<- buffer%>%filter(Landscape_ == "132_Mexico_north america_15.15874_-92.31623")
buffer132_1<-st_sf(buffer132_1)
st_crs(buffer132_1)
buffer132_1<- st_transform(buffer132_1, crs = 4326)
plot(buffer132_1["Country"])
study_132_1<- st_read("Vectores_2001-2010_07.17/L5vector_study_132_1.shp")
study_132_1<-st_sf(study_132_1)
study_132_1<- st_transform(study_132_1, crs = 4326)
plot(study_132_1["classNames"], col= c("yellow","green",  "red"))
class(study_132_1)
class(buffer132_1)
join132_1 <- st_join(study_132_1, buffer132_1["Landscape_"], left = TRUE) # join points
join132_1<-st_sf(join133_3)
join132_1<- st_transform(join132_1, crs = 4326)
st_as_sf(join132_1)
print(join132_1)
class(join132_1)
area132_1<- join132_1%>%mutate(area_m2 =st_area(join132_1))
class(area132_1)
area132_1_df<- fortify(area132_1)
area132_1_df<- as.data.frame(area132_1_df) %>% dplyr::select(1:3,5)

natural.join132_1<- natural.join2001_2010%>%filter(Landscape_ == "132_Mexico_north america_15.15874_-92.31623")
point132_1<- point2001_2010%>%filter(Landscape_ == "132_Mexico_north america_15.15874_-92.31623")
near.point132_1<- st_nearest_points(point132_1, natural.join132_1)
class(near.point132_1)
near.point132_1<-st_sf(near.point132_1)
near.point132_1<- st_transform(near.point132_1, crs = 4326)
near.point132_1$length<- st_length(near.point132_1)
near.point132_1<-st_sf(near.point132_1)
near.point132_1<- st_transform(near.point132_1, crs = 4326)

class(near.point132_1)
class(point132_1)
distance.join132_1 <- st_join(near.point132_1, point132_1["Landscape_"], left = TRUE) # join points
distance.join132_1<-st_sf(distance.join132_1)
distance.join132_1<- st_transform(distance.join132_1, crs = 4326)
st_as_sf(distance.join132_1)
print(distance.join132_1)
class(distance.join132_1)

distance.join132_1.df<- fortify(distance.join132_1)
distance.join132_1.df<- as.data.frame(distance.join132_1.df)%>%dplyr::select(1:2)

min_distance132_1<- distance.join132_1.df%>%group_by(Landscape_)%>%
  mutate(min_distance = min(length))%>%
  distinct(Landscape_, .keep_all = TRUE)

data132_1_df<- right_join(x=min_distance132_1 , y=area132_1_df, by="Landscape_")

#551, 552, 585, 743 (15.16666667	-92.31666667)
buffer551_552_585_743<- buffer%>%filter(Landscape_ == "552_Mexico_north america_15.16666667_-92.31666667"|
                                          Landscape_ == "551_Mexico_north america_15.16666667_-92.31666667"|
                                          Landscape_ == "585_Mexico_north america_15.16666667_-92.31666667"|
                                          Landscape_ == "743_Mexico_north america_15.16666667_-92.31666667")
buffer551_552_585_743<-st_sf(buffer551_552_585_743)
st_crs(buffer551_552_585_743)
buffer551_552_585_743<- st_transform(buffer551_552_585_743, crs = 4326)
plot(buffer551_552_585_743["Country"])
study551_552_585_743<- st_read("Vectores_2001-2010_07.17/L5vector_study_551_2_552_2_3_585_4_743_2.shp")
names(study551_552_585_743)
study551_552_585_743<-st_sf(study551_552_585_743)
study551_552_585_743<- st_transform(study551_552_585_743, crs = 4326)
plot(study551_552_585_743["classNames"], col= c("yellow","green",  "red"))
class(study551_552_585_743)
class(buffer551_552_585_743)
join551_552_585_743 <- st_join(study551_552_585_743, buffer551_552_585_743["Landscape_"], left = TRUE) # join points
join551_552_585_743<-st_sf(join551_552_585_743)
join551_552_585_743<- st_transform(join551_552_585_743, crs = 4326)
st_as_sf(join551_552_585_743)
print(join551_552_585_743)
class(join551_552_585_743)
area551_552_585_743<- join551_552_585_743%>%mutate(area_m2 =st_area(join551_552_585_743))
class(area551_552_585_743)
area551_552_585_743_df<- fortify(area551_552_585_743)
area551_552_585_743_df<- as.data.frame(area551_552_585_743_df) %>% dplyr::select(1:3,5)

natural.join551_552_585_743<- natural.join2001_2010%>%filter(Landscape_ == "552_Mexico_north america_15.16666667_-92.31666667"|
                                                               Landscape_ == "551_Mexico_north america_15.16666667_-92.31666667"|
                                                               Landscape_ == "585_Mexico_north america_15.16666667_-92.31666667"|
                                                               Landscape_ == "743_Mexico_north america_15.16666667_-92.31666667")
point551_552_585_743<- point2001_2010%>%filter(Landscape_ == "552_Mexico_north america_15.16666667_-92.31666667"|
                                                 Landscape_ == "551_Mexico_north america_15.16666667_-92.31666667"|
                                                 Landscape_ == "585_Mexico_north america_15.16666667_-92.31666667"|
                                                 Landscape_ == "743_Mexico_north america_15.16666667_-92.31666667")
near.point551_552_585_743<- st_nearest_points(point551_552_585_743, natural.join551_552_585_743)
class(near.point551_552_585_743)
near.point551_552_585_743<-st_sf(near.point551_552_585_743)
near.point551_552_585_743<- st_transform(near.point551_552_585_743, crs = 4326)
near.point551_552_585_743$length<- st_length(near.point551_552_585_743)
near.point551_552_585_743<-st_sf(near.point551_552_585_743)
near.point551_552_585_743<- st_transform(near.point551_552_585_743, crs = 4326)

class(near.point551_552_585_743)
class(point551_552_585_743)
distance.join551_552_585_743 <- st_join(near.point551_552_585_743, point551_552_585_743["Landscape_"], left = TRUE) # join points
distance.join551_552_585_743<-st_sf(distance.join551_552_585_743)
distance.join551_552_585_743<- st_transform(distance.join551_552_585_743, crs = 4326)
st_as_sf(distance.join551_552_585_743)
print(distance.join551_552_585_743)
class(distance.join551_552_585_743)

distance.join551_552_585_743.df<- fortify(distance.join551_552_585_743)
distance.join551_552_585_743.df<- as.data.frame(distance.join551_552_585_743.df)%>%dplyr::select(1:2)

min_distance551_552_585_743<- distance.join551_552_585_743.df%>%group_by(Landscape_)%>%
  mutate(min_distance = min(length))%>%
  distinct(Landscape_, .keep_all = TRUE)

data551_552_585_743_df<- right_join(x=min_distance551_552_585_743 , y=area551_552_585_743_df, by="Landscape_")

#551, 552, 585 (15.18333333	-92.33333333)
buffer551_552_585<- buffer%>%filter(Landscape_ == "551_Mexico_north america_15.18333333_-92.33333333"|
                                      Landscape_ == "552_Mexico_north america_15.18333333_-92.33333333"|
                                      Landscape_ == "585_Mexico_north america_15.18333333_-92.33333333")
buffer551_552_585<-st_sf(buffer551_552_585)
st_crs(buffer551_552_585)
buffer551_552_585<- st_transform(buffer551_552_585, crs = 4326)
plot(buffer551_552_585["Country"])
study551_552_585<- st_read("Vectores_2001-2010_07.17/L5vector_study_551_1_552_1_585_2.shp")
study551_552_585<-st_sf(study551_552_585)
study551_552_585<- st_transform(study551_552_585, crs = 4326)
plot(study551_552_585["classNames"], col= c("yellow","green",  "red"))
class(study551_552_585)
class(buffer551_552_585)
join551_552_585 <- st_join(study551_552_585, buffer551_552_585["Landscape_"], left = TRUE) # join points
join551_552_585<-st_sf(join551_552_585)
join551_552_585<- st_transform(join551_552_585, crs = 4326)
st_as_sf(join551_552_585)
print(join551_552_585)
class(join551_552_585)
area551_552_585<- join551_552_585%>%mutate(area_m2 =st_area(join551_552_585))
class(area551_552_585)
area551_552_585_df<- fortify(area551_552_585)
area551_552_585_df<- as.data.frame(area551_552_585_df) %>% dplyr::select(1:3,5)

natural.join551_552_585<- natural.join2001_2010%>%filter(Landscape_ == "551_Mexico_north america_15.18333333_-92.33333333"|
                                                           Landscape_ == "552_Mexico_north america_15.18333333_-92.33333333"|
                                                           Landscape_ == "585_Mexico_north america_15.18333333_-92.33333333")
point551_552_585<- point2001_2010%>%filter(Landscape_ == "551_Mexico_north america_15.18333333_-92.33333333"|
                                             Landscape_ == "552_Mexico_north america_15.18333333_-92.33333333"|
                                             Landscape_ == "585_Mexico_north america_15.18333333_-92.33333333")
near.point551_552_585<- st_nearest_points(point551_552_585, natural.join551_552_585)
class(near.point551_552_585)
near.point551_552_585<-st_sf(near.point551_552_585)
near.point551_552_585<- st_transform(near.point551_552_585, crs = 4326)
near.point551_552_585$length<- st_length(near.point551_552_585)
near.point551_552_585<-st_sf(near.point551_552_585)
near.point551_552_585<- st_transform(near.point551_552_585, crs = 4326)

class(near.point551_552_585)
class(point551_552_585)
distance.join551_552_585 <- st_join(near.point551_552_585, point551_552_585["Landscape_"], left = TRUE) # join points
distance.join551_552_585<-st_sf(distance.join551_552_585)
distance.join551_552_585<- st_transform(distance.join551_552_585, crs = 4326)
st_as_sf(distance.join551_552_585)
print(distance.join551_552_585)
class(distance.join551_552_585)

distance.join551_552_585.df<- fortify(distance.join551_552_585)
distance.join551_552_585.df<- as.data.frame(distance.join551_552_585.df)%>%dplyr::select(1:2)

min_distance551_552_585<- distance.join551_552_585.df%>%group_by(Landscape_)%>%
  mutate(min_distance = min(length))%>%
  distinct(Landscape_, .keep_all = TRUE)

data551_552_585_df<- right_join(x=min_distance551_552_585, y=area551_552_585_df, by="Landscape_")

#34 (-1.50886222 120.0347222)
buffer34<- buffer%>%filter(Landscape_ == "34_Indonesia_asia_-1.50886222_120.0347222")
buffer34<-st_sf(buffer34)
st_crs(buffer34)
buffer34<- st_transform(buffer34, crs = 4326)
plot(buffer34["Country"])
study34<- st_read("Vectores_2001-2010_07.17/L5vector_study_34.shp")
study34<-st_sf(study34)
study34<- st_transform(study34, crs = 4326)
plot(study34["classNames"], col= c("yellow","green",  "red"))
class(study34)
class(study34)
join34 <- st_join(study34, buffer34["Landscape_"], left = TRUE) # join points
join34<-st_sf(join34)
join34<- st_transform(join34, crs = 4326)
st_as_sf(join34)
print(join34)
class(join34)
area34<- join34%>%mutate(area_m2 =st_area(join34))
class(area34)
area34_df<- fortify(area34)
area34_df<- as.data.frame(area34_df) %>% dplyr::select(1:3,5)

natural.join34<- natural.join2001_2010%>%filter(Landscape_ == "34_Indonesia_asia_-1.50886222_120.0347222")
point34<- point2001_2010%>%filter(Landscape_ == "34_Indonesia_asia_-1.50886222_120.0347222")

near.point34<- st_nearest_points(point34, natural.join34)
class(near.point34)
near.point34<-st_sf(near.point34)
near.point34<- st_transform(near.point34, crs = 4326)
near.point34$length<- st_length(near.point34)
near.point34<-st_sf(near.point34)
near.point34<- st_transform(near.point34, crs = 4326)

class(near.point34)
class(point551_552_585)
distance.join34 <- st_join(near.point34, point551_552_585["Landscape_"], left = TRUE) # join points
distance.join34<-st_sf(distance.join34)
distance.join34<- st_transform(distance.join34, crs = 4326)
st_as_sf(distance.join34)
print(distance.join34)
class(distance.join34)

distance.join34.df<- fortify(distance.join34)
distance.join34.df<- as.data.frame(distance.join34.df)%>%dplyr::select(1:2)

min_distance34<- distance.join34.df%>%group_by(Landscape_)%>%
  mutate(min_distance = min(length))%>%
  distinct(Landscape_, .keep_all = TRUE)

data34_df<- right_join(x=min_distance34, y=area34_df, by="Landscape_")

#550 (-1.5 120.035) FALTA AGREGAR EL PUNTO 1040
buffer550_1040<- buffer%>%filter(Landscape_ == "550_Indonesia_asia_-1.5_120.035"|
                                   Landscape_ == "1040_Indonesia_asia_-1.5_120.035")
buffer550_1040<-st_sf(buffer550_1040)
st_crs(buffer550_1040)
buffer550_1040<- st_transform(buffer550_1040, crs = 4326)
plot(buffer550_1040["Country"])
study550_1040<- st_read("Vectores_2001-2010_07.17/L5vector_study_550_1040.shp")
study550_1040<-st_sf(study550_1040)
study550_1040<- st_transform(study550_1040, crs = 4326)
plot(study550_1040["classNames"], col= c("yellow","green",  "red"))
class(study550_1040)
class(buffer550_1040)
join550_1040 <- st_join(study550_1040, buffer550_1040["Landscape_"], left = TRUE) # join points
join550_1040<-st_sf(join550_1040)
join550_1040<- st_transform(join550_1040, crs = 4326)
st_as_sf(join550_1040)
print(join550_1040)
class(join550_1040)
area550_1040<- join550_1040%>%mutate(area_m2 =st_area(join550_1040))
class(area550_1040)
area550_1040_df<- fortify(area550_1040)
area550_1040_df<- as.data.frame(area550_1040_df) %>% dplyr::select(1:3,5)

natural.join550_1040<- natural.join2001_2010%>%filter(Landscape_ == "550_Indonesia_asia_-1.5_120.035")
point550_1040<- point2001_2010%>%filter(Landscape_ == "550_Indonesia_asia_-1.5_120.035")

near.point550_1040<- st_nearest_points(point550_1040, natural.join550_1040)
class(near.point550_1040)
near.point550_1040<-st_sf(near.point550_1040)
near.point550_1040<- st_transform(near.point550_1040, crs = 4326)
near.point550_1040$length<- st_length(near.point550_1040)
near.point550_1040<-st_sf(near.point550_1040)
near.point550_1040<- st_transform(near.point550_1040, crs = 4326)

class(near.point550_1040)
class(point550_1040)
distance.join550_1040 <- st_join(near.point550_1040, point550_1040["Landscape_"], left = TRUE) # join points
distance.join550_1040<-st_sf(distance.join550_1040)
distance.join550_1040<- st_transform(distance.join550_1040, crs = 4326)
st_as_sf(distance.join550_1040)
print(distance.join550_1040)
class(distance.join550_1040)

distance.join550_1040.df<- fortify(distance.join550_1040)
distance.join550_1040.df<- as.data.frame(distance.join550_1040.df)%>%dplyr::select(1:2)

min_distance550_1040<- distance.join550_1040.df%>%group_by(Landscape_)%>%
  mutate(min_distance = min(length))%>%
  distinct(Landscape_, .keep_all = TRUE)

data550_1040_df<- right_join(x=min_distance550_1040, y=area550_1040_df, by="Landscape_")

#557 (-1.506666667 120.0363889)
buffer557<- buffer%>%filter(Landscape_ == "557_Indonesia_asia_-1.506666667_120.0363889")
buffer557<-st_sf(buffer557)
st_crs(buffer557)
buffer557<- st_transform(buffer557, crs = 4326)
plot(buffer557["Country"])
study557<- st_read("Vectores_2001-2010_07.17/L5vector_study_557.shp")
study557<-st_sf(study557)
study557<- st_transform(study557, crs = 4326)
plot(study557["classNames"], col= c("yellow","green",  "red"))
class(study557)
class(buffer557)
join557 <- st_join(study557, buffer557["Landscape_"], left = TRUE) # join points
join557<-st_sf(join557)
join557<- st_transform(join557, crs = 4326)
st_as_sf(join557)
print(join557)
class(join557)
area557<- join557%>%mutate(area_m2 =st_area(join557))
class(area557)
area557_df<- fortify(area557)
area557_df<- as.data.frame(area557_df) %>% dplyr::select(1:3,5)

natural.join557<- natural.join2001_2010%>%filter(Landscape_ == "557_Indonesia_asia_-1.506666667_120.0363889")
point557<- point2001_2010%>%filter(Landscape_ == "557_Indonesia_asia_-1.506666667_120.0363889")

near.point557<- st_nearest_points(point557, natural.join557)
class(near.point557)
near.point557<-st_sf(near.point557)
near.point557<- st_transform(near.point557, crs = 4326)
near.point557$length<- st_length(near.point557)
near.point557<-st_sf(near.point557)
near.point557<- st_transform(near.point557, crs = 4326)

class(near.point557)
class(point557)
distance.join557 <- st_join(near.point557, point557["Landscape_"], left = TRUE) # join points
distance.join557<-st_sf(distance.join557)
distance.join557<- st_transform(distance.join557, crs = 4326)
st_as_sf(distance.join557)
print(distance.join557)
class(distance.join557)

distance.join557.df<- fortify(distance.join557)
distance.join557.df<- as.data.frame(distance.join557.df)%>%dplyr::select(1:2)

min_distance557<- distance.join557.df%>%group_by(Landscape_)%>%
  mutate(min_distance = min(length))%>%
  distinct(Landscape_, .keep_all = TRUE)

data557_df<- right_join(x=min_distance557, y=area557_df, by="Landscape_")

#743 (15.16666667	-92.33333333)
buffer743<- buffer%>%filter(Landscape_ == "743_Mexico_north america_15.16666667_-92.33333333")
buffer743<-st_sf(buffer743)
st_crs(buffer743)
buffer743<- st_transform(buffer743, crs = 4326)
plot(buffer743["Country"])
study743<- st_read("Vectores_2001-2010_07.17/L5vector_study_743_1.shp")
study743<-st_sf(study743)
study743<- st_transform(study743, crs = 4326)
plot(study743["classNames"], col= c("yellow","green",  "red"))
class(study743)
class(buffer743)
join743 <- st_join(study743, buffer743["Landscape_"], left = TRUE) # join points
join743<-st_sf(join743)
join743<- st_transform(join743, crs = 4326)
st_as_sf(join743)
print(join743)
class(join743)
area743<- join743%>%mutate(area_m2 =st_area(join743))
class(area743)
area743_df<- fortify(area743)
area743_df<- as.data.frame(area743_df) %>% dplyr::select(1:3,5)

natural.join743<- natural.join2001_2010%>%filter(Landscape_ == "743_Mexico_north america_15.16666667_-92.33333333")
point743<- point2001_2010%>%filter(Landscape_ == "743_Mexico_north america_15.16666667_-92.33333333")

near.point743<- st_nearest_points(point743, natural.join743)
class(near.point743)
near.point743<-st_sf(near.point743)
near.point743<- st_transform(near.point743, crs = 4326)
near.point743$length<- st_length(near.point743)
near.point743<-st_sf(near.point743)
near.point743<- st_transform(near.point743, crs = 4326)

class(near.point743)
class(point743)
distance.join743 <- st_join(near.point743, point743["Landscape_"], left = TRUE) # join points
distance.join743<-st_sf(distance.join743)
distance.join743<- st_transform(distance.join743, crs = 4326)
st_as_sf(distance.join743)
print(distance.join743)
class(distance.join743)

distance.join743.df<- fortify(distance.join743)
distance.join743.df<- as.data.frame(distance.join743.df)%>%dplyr::select(1:2)

min_distance743<- distance.join743.df%>%group_by(Landscape_)%>%
  mutate(min_distance = min(length))%>%
  distinct(Landscape_, .keep_all = TRUE)

data743_df<- right_join(x=min_distance743, y=area743_df, by="Landscape_")

#585 ()
buffer585_3<- buffer%>%filter(Landscape_ == "585_Mexico_north america_15.25_-92.38333333")
buffer585_3<-st_sf(buffer585_3)
st_crs(buffer585_3)
buffer585_3<- st_transform(buffer585_3, crs = 4326)
plot(buffer585_3["Country"])
study585_3<- st_read("Vectores_2001-2010_07.17/L5vector_study_585_3.shp")
study585_3<-st_sf(study585_3)
study585_3<- st_transform(study585_3, crs = 4326)
plot(study585_3["classNames"], col= c("yellow","green",  "red"))
class(study585_3)
class(buffer585_3)
join585_3 <- st_join(study585_3, buffer585_3["Landscape_"], left = TRUE) # join points
join585_3<-st_sf(join585_3)
join585_3<- st_transform(join585_3, crs = 4326)
st_as_sf(join585_3)
print(join585_3)
class(join585_3)
area585_3<- join585_3%>%mutate(area_m2 =st_area(join585_3))
class(area585_3)
area585_3_df<- fortify(area585_3)
area585_3_df<- as.data.frame(area585_3_df) %>% dplyr::select(1:3,5)

natural.join585_3<- natural.join2001_2010%>%filter(Landscape_ == "585_Mexico_north america_15.25_-92.38333333")
point585_3<- point2001_2010%>%filter(Landscape_ == "585_Mexico_north america_15.25_-92.38333333")

near.point585_3<- st_nearest_points(point585_3, natural.join585_3)
class(near.point585_3)
near.point585_3<-st_sf(near.point585_3)
near.point585_3<- st_transform(near.point585_3, crs = 4326)
near.point585_3$length<- st_length(near.point585_3)
near.point585_3<-st_sf(near.point585_3)
near.point585_3<- st_transform(near.point585_3, crs = 4326)

class(near.point585_3)
class(point585_3)
distance.join585_3 <- st_join(near.point585_3, point585_3["Landscape_"], left = TRUE) # join points
distance.join585_3<-st_sf(distance.join585_3)
distance.join585_3<- st_transform(distance.join585_3, crs = 4326)
st_as_sf(distance.join585_3)
print(distance.join585_3)
class(distance.join585_3)

distance.join585_3.df<- fortify(distance.join585_3)
distance.join585_3.df<- as.data.frame(distance.join585_3.df)%>%dplyr::select(1:2)

min_distance585_3<- distance.join585_3.df%>%group_by(Landscape_)%>%
  mutate(min_distance = min(length))%>%
  distinct(Landscape_, .keep_all = TRUE)

data585_3_df<- right_join(x=min_distance585_3, y=area585_3_df, by="Landscape_")

#585 (15.25 -92.38333333)
buffer585_1<- buffer%>%filter(Landscape_ == "585_Mexico_north america_15.25_-92.36666667")
buffer585_1<-st_sf(buffer585_1)
st_crs(buffer585_1)
buffer585_1<- st_transform(buffer585_1, crs = 4326)
plot(buffer585_1["Country"])
study585_1<- st_read("Vectores_2001-2010_07.17/L5vector_study_585_1.shp")
study585_1<-st_sf(study585_1)
study585_1<- st_transform(study585_1, crs = 4326)
plot(study585_1["classNames"], col= c("yellow","green",  "red"))
class(study585_1)
class(buffer585_1)
join585_1 <- st_join(study585_1, buffer585_1["Landscape_"], left = TRUE) # join points
join585_1<-st_sf(join585_1)
join585_1<- st_transform(join585_1, crs = 4326)
st_as_sf(join585_1)
print(join585_1)
class(join585_1)
area585_1<- join585_1%>%mutate(area_m2 =st_area(join585_1))
class(area585_1)
area585_1_df<- fortify(area585_1)
area585_1_df<- as.data.frame(area585_1_df) %>% dplyr::select(1:3,5)

natural.join585_1<- natural.join2001_2010%>%filter(Landscape_ == "585_Mexico_north america_15.25_-92.36666667")
point585_1<- point2001_2010%>%filter(Landscape_ == "585_Mexico_north america_15.25_-92.36666667")

near.point585_1<- st_nearest_points(point585_1, natural.join585_1)
class(near.point585_1)
near.point585_1<-st_sf(near.point585_1)
near.point585_1<- st_transform(near.point585_1, crs = 4326)
near.point585_1$length<- st_length(near.point585_1)
near.point585_1<-st_sf(near.point585_1)
near.point585_1<- st_transform(near.point585_1, crs = 4326)

class(near.point585_1)
class(point585_1)
distance.join585_1 <- st_join(near.point585_1, point585_1["Landscape_"], left = TRUE) # join points
distance.join585_1<-st_sf(distance.join585_1)
distance.join585_1<- st_transform(distance.join585_1, crs = 4326)
st_as_sf(distance.join585_1)
print(distance.join585_1)
class(distance.join585_1)

distance.join585_1.df<- fortify(distance.join585_1)
distance.join585_1.df<- as.data.frame(distance.join585_1.df)%>%dplyr::select(1:2)

min_distance585_1<- distance.join585_1.df%>%group_by(Landscape_)%>%
  mutate(min_distance = min(length))%>%
  distinct(Landscape_, .keep_all = TRUE)

data585_1_df<- right_join(x=min_distance585_1, y=area585_1_df, by="Landscape_")

###Join area and distance databases
#2011-2019
data2011_2019_df<- right_join(x=min_distance2011_2019 , y=area2011_2019_df, by="Landscape_")%>%
  dplyr::filter(Landscape_ != "133_Mexico_north america_19.20611111_-96.88444444",
                Landscape_ != "133_Mexico_north america_19.21583333_-96.88527778",
                Landscape_ !="133_Mexico_north america_19.46638889_-96.93416667",
                Landscape_ != "18_Mexico_north america_19.455055_-96.92654")%>%
  dplyr::bind_rows(data133_2_df, data133_5_df, data133_3_df, data18_2_df)
class(data2011_2019_df)


#2001-2010
data2001_2010_df<- right_join(x=min_distance2001_2010 , y=area2001_2010_df, by="Landscape_")%>%
  dplyr::filter(Landscape_ != "132_Mexico_north america_15.15874_-92.31623",
                Landscape_ != "552_Mexico_north america_15.16666667_-92.31666667",
                Landscape_ != "551_Mexico_north america_15.16666667_-92.31666667",
                Landscape_ != "585_Mexico_north america_15.16666667_-92.31666667",
                Landscape_ != "743_Mexico_north america_15.16666667_-92.31666667",
                Landscape_ != "551_Mexico_north america_15.18333333_-92.33333333",
                Landscape_ != "552_Mexico_north america_15.18333333_-92.33333333",
                Landscape_ != "585_Mexico_north america_15.18333333_-92.33333333",
                Landscape_ != "34_Indonesia_asia_-1.50886222_120.0347222",
                Landscape_ != "550_Indonesia_asia_-1.5_120.035",
                Landscape_ != "557_Indonesia_asia_-1.506666667_120.0363889",
                Landscape_ != "1040_Indonesia_asia_-1.5_120.035",
                Landscape_ != "743_Mexico_north america_15.16666667_-92.33333333",
                Landscape_ != "585_Mexico_north america_15.25_-92.38333333",
                Landscape_ != "585_Mexico_north america_15.25_-92.36666667")%>%
  dplyr::bind_rows(data132_1_df, data551_552_585_743_df, data551_552_585_df, data34_df, 
                   data550_1040_df, data557_df, data743_df, data585_3_df, data585_1_df)
class(data2001_2010_df)

#1986-2000
data1986_2000_df<- right_join(x=min_distance1986_2000 , y=area1986_2000_df, by="Landscape_")
class(data1986_2000_df)

##Export the area2011_2019
#2011-2019
write.csv(data2011_2019_df, "data2011_2019_07_18.csv")

#2001-2010
write.csv(data2001_2010_df, "data2001_2010_07_18.csv")

#1986-2000
write.csv(data1986_2000_df, "data1986_2000_07_18.csv")